substitutions:
  board: esp32-c6-devkitc-1
  framework: esp-idf
  ap_ssid: "Jukebox"
  home_assistant_api_encryption_key: !secret jukebox_home_assistant_api_encryption_key
  ota_password: !secret jukebox_ota_password

esphome:
  name: jukebox
  friendly_name: Jukebox

packages:
  - !include packages/base.package.yaml
  - !include packages/jukebox/nfc.package.yaml
