# Get info from HA, as string format
text_sensor:
  - platform: homeassistant
    entity_id: weather.smhi_home
    id: myWeather
    internal: true
  - platform: homeassistant
    entity_id: weather.smhi_home
    id: myTemperature
    attribute: "temperature"
    internal: true
  - platform: homeassistant
    entity_id: sensor.current_date
    id: current_date
    internal: true
  - platform: homeassistant
    entity_id: sensor.expected_rain
    id: expected_rain
    internal: true
  - platform: homeassistant
    entity_id: sensor.openuv_current_uv_index
    id: uv_index
    internal: true
  # Word of the day sensors
  - platform: homeassistant
    entity_id: sensor.word_of_the_day
    id: myIcelandicWord
    attribute: "fletta"
    internal: true
  - platform: homeassistant
    entity_id: sensor.word_of_the_day_translations
    id: word_translations
    internal: true
  - platform: homeassistant
    entity_id: sensor.word_of_the_day_example_1_is
    id: word_example1_is
    internal: true
  - platform: homeassistant
    entity_id: sensor.word_of_the_day_example_1_se
    id: word_example1_se
    internal: true
  - platform: homeassistant
    entity_id: sensor.word_of_the_day_example_2_is
    id: word_example2_is
    internal: true
  - platform: homeassistant
    entity_id: sensor.word_of_the_day_example_2_se
    id: word_example2_se
    internal: true

sensor:
  - platform: adc
    id: battery_adc
    update_interval: never
    pin: GPIO1
    attenuation: 12db
    samples: 5
    entity_category: "diagnostic"
    accuracy_decimals: 2
    device_class: battery
    unit_of_measurement: "V"
    internal: true
    filters:
      - multiply: 2
  - platform: template
    id: battery_percent
    name: "Battery Percentage"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    update_interval: never
    lambda: |-
      return voltage_to_battery_percent(id(battery_adc).state);
